//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLaborEfficiencyWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cr_Baan
    {
        public int id { get; set; }
        public string PONUMBER { get; set; }
        public string SUPPLIERNBR { get; set; }
        public string POTYPE { get; set; }
        public string BUYER { get; set; }
        public string REFERENCEA { get; set; }
        public string REFERENCEB { get; set; }
        public string ITEM { get; set; }
        public string ITEMDSE { get; set; }
        public Nullable<int> QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public string CompCode { get; set; }
    }
}
