//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLaborEfficiencyWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CommodityRecvCmp
    {
        public string PONUMBER { get; set; }
        public string ITEM { get; set; }
        public Nullable<int> Qty { get; set; }
        public string UNIT { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public string CompCode { get; set; }
        public string CommodityCodeDescription { get; set; }
    }
}
