//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLaborEfficiencyWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_role_rights
    {
        public int id { get; set; }
        public string RefRoleID { get; set; }
        public string RightName { get; set; }
        public string RightContent { get; set; }
    }
}
