//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLaborEfficiencyWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tbl_WeekData
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public string Warehouse { get; set; }
        public Nullable<int> HC_FCST { get; set; }
        public Nullable<int> HC_Actual { get; set; }
        public Nullable<int> HC_Support { get; set; }
        public Nullable<decimal> HC_Utilization { get; set; }
        public Nullable<int> Case_ID_in { get; set; }
        public Nullable<int> Case_ID_out { get; set; }
        public Nullable<int> Pallet_In { get; set; }
        public Nullable<int> Pallet_Out { get; set; }
        public Nullable<int> Jobs_Rec { get; set; }
        public Nullable<int> Jobs_Issue { get; set; }
        public Nullable<int> Reel_ID_Rec { get; set; }
    }
}
